after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-left = 'focus --boundaries workspace --boundaries-action wrap-around-the-workspace left'
alt-shift-right = 'focus --boundaries workspace --boundaries-action wrap-around-the-workspace right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-b = 'workspace B'
alt-d = 'workspace D'
alt-e = 'workspace E'
alt-n = 'workspace N'
alt-p = 'workspace P'
alt-t = 'workspace T'
alt-v = 'workspace V'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-v = 'move-node-to-workspace V'

alt-shift-f = 'fullscreen'
ctrl-alt-r = 'balance-sizes'
alt-tab = 'workspace-back-and-forth'

alt-semicolon = 'mode service'
alt-backslash = 'mode resize'

[mode.resize.binding]
h = 'resize smart -50'
j = 'resize smart -50'
k = 'resize smart +50'
l = 'resize smart +50'
shift-h = 'resize width -50'
shift-j = 'resize height +50'
shift-k = 'resize height -50'
shift-l = 'resize width +50'
b = 'balance-sizes'
enter = 'mode main'
esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace N"
